=head1 Twist

Twist is a minimalistic blogging application built on top of L<Dancer>.

=head2 Features

=over

    * filesystem-based storage
    * comments (via Disqus)
    * tags
    * RSS (articles, tags)
    * static pages
    * drafts
    * archive
    * Unicode support

    * lightweight
    * clean code
    * runs everywhere

=back

=head2 Famous 5 seconds setup

    $ git clone http://github.com/vti/twist.git
    $ cd twist
    $ plackup bin/app.pl
    Server available at http://*:5000.

=head2 Configuration

Copy C<config.yml.sample> to C<config.yml> and change it to fit your needs.

=head2 Writing articles

Articles by default go into C<articles/> directory.

Article consists of file information and content with meta data.

=head3 File info

    20101017-article.pod

    or

    20101017T14:02:00-article.pod

Where timestamp tells us when the article was created. Modified time is
retrieved automatically from C<mtime>. Filename is the article's permalink url.
Extention is article's format.

=head3 Content

    Title: My first article
    Tags: blog, internet

    Welcome!

    [cut] Read more

    This is my first article. It is in C<pod> format. And I can use all kind of
    B<tags>.

Every article should have metadata. Metadata ends with an empty line. If there
is a C<[cut]> tag, article will be splitted into C<preview> and C<content>
parts. C<preview> is shown when a) article list is requested, b) rss.

=head2 Drafts

Drafts are available under C</drafts> url. Only you know the title, so it is
safe to put there your drafts and refresh browser to see how it looks.

=head2 Static pages

Just put a C<pod> into C<pages/> directory. Pages are available under C</pages>
url.
